<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Security package for user input sanitzation IdentityServer8 services and packages.</Description>
    <IsPackable>true</IsPackable>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyVersion>8.0.5.0</AssemblyVersion>
    <FileVersion>8.0.5.0</FileVersion>
    <InformationalVersion>8.0.5-pazofrc004</InformationalVersion>
    <Version>8.0.5-pazofrc004</Version>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>