<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Security package for user input sanitzation IdentityServer8 services and packages.</Description>
    <IsPackable>true</IsPackable>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyVersion>8.1.0.0</AssemblyVersion>
    <FileVersion>8.1.0.0</FileVersion>
    <InformationalVersion>8.1.0-alpha.175+Branch.develop.Sha.7fee13a586758ad39dd800c6806f88d4fe604e7c</InformationalVersion>
    <Version>8.1.0-alpha.175</Version>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>