<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Storage interfaces and models for IdentityServer8</Description>
    <IsPackable>true</IsPackable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <AssemblyVersion>8.1.0.0</AssemblyVersion>
    <FileVersion>8.1.0.0</FileVersion>
    <InformationalVersion>8.1.0-alpha.175+Branch.develop.Sha.7fee13a586758ad39dd800c6806f88d4fe604e7c</InformationalVersion>
    <Version>8.1.0-alpha.175</Version>
  </PropertyGroup>
  <PropertyGroup>
    <ContinuousIntegrationBuild Condition="'$(TF_BUILD)' == 'true'">True</ContinuousIntegrationBuild>
    <ContinuousIntegrationBuild Condition="'$(GITHUB_ACTIONS)' == 'true'">True</ContinuousIntegrationBuild>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\..\..\icon.jpg">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="IdentityModel" />
    <PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>
</Project>