<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>EntityFramework persistence layer for IdentityServer8</Description>
    <IsPackable>true</IsPackable>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <AssemblyVersion>8.1.0.0</AssemblyVersion>
    <FileVersion>8.1.0.0</FileVersion>
    <InformationalVersion>8.1.0-alpha.171+Branch.develop.Sha.da2987cb01112daf4921052899b0e1ba7d228de4</InformationalVersion>
    <Version>8.1.0-alpha.171</Version>
  </PropertyGroup>
  <PropertyGroup>
    <ContinuousIntegrationBuild Condition="'$(TF_BUILD)' == 'true'">True</ContinuousIntegrationBuild>
    <ContinuousIntegrationBuild Condition="'$(GITHUB_ACTIONS)' == 'true'">True</ContinuousIntegrationBuild>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\EntityFramework.Storage\src\IdentityServer8.EntityFramework.Storage.csproj" />
    <ProjectReference Include="..\..\IdentityServer8\src\IdentityServer8.csproj" />
  </ItemGroup>
</Project>