<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <AssemblyVersion>8.1.0.0</AssemblyVersion>
    <FileVersion>8.1.0.0</FileVersion>
    <InformationalVersion>8.1.0-alpha.175+Branch.develop.Sha.7fee13a586758ad39dd800c6806f88d4fe604e7c</InformationalVersion>
    <Version>8.1.0-alpha.175</Version>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="coverlet.collector" GeneratePathProperty="true">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\IdentityServer8.EntityFramework.csproj" />
  </ItemGroup>
</Project>